Repository shopware/docs, pull requests merged in 2022-07, with the labels that each got.

#611 Update filesystem.md
  guides/plugins/plugins/framework/filesystem/filesystem.md
Labels: Core Team

#552 NEXT-20418 - Add additional app privileges to manifest reference
  guides/plugins/apps/app-base-guide.md
  resources/references/app-reference/manifest-reference.md
Labels: Core Team, Improvement

#548 Fixing various issues with the MailTemplate Migration
  guides/plugins/plugins/content/mail/add-mail-template.md
Labels: Improvement

#523 Use "tested on" instead of min requirements
  guides/installation/overview.md
Labels: Improvement

#504 NEXT-16624 - Updated the documentation about creating a modal due to …
  guides/plugins/plugins/storefront/using-a-modal-window.md
Labels: Core Team, Blocked

#549 NEXT-21055 - added docs for app rule conditions
  .gitbook/assets/app-rule-condition.png
  SUMMARY.md
  concepts/extensions/apps-concept.md
  guides/plugins/apps/rule-builder/README.md
  guides/plugins/apps/rule-builder/add-custom-rule-conditions.md
  resources/references/app-reference/manifest-reference.md
Labels: Core Team, Guide
