Repository shopware/docs, pull requests merged in 2022-04, with the labels that each got.

#538 B2B-870 - B2B-Suite administration docs
  SUMMARY.md
  products/editions/enterprise-edition/b2b-suite/administration/administration.md
Labels: Enterprise Team, Guide

#530 NEXT-20885 - Add webhook eventId docs
  guides/plugins/apps/app-base-guide.md
Labels: Core Team

#556 fix: add option for updating plugin in migration
  guides/plugins/plugins/storefront/add-custom-sorting-product-listing.md
Labels: Improvement

#536 Fix Add cms block Storefront representation guide
  guides/plugins/plugins/content/cms/add-cms-block.md
Labels: Improvement

#557 add information when this feature is available
  guides/hosting/performance/performance-tweaks.md
Labels: Improvement

#533 B2B-869 - Add concepts
  .gitbook/assets/b2b-architecture-acl.svg
  .gitbook/assets/b2b-architecture-component.svg
  .gitbook/assets/b2b-architecture-components-complete.svg
  .gitbook/assets/b2b-architecture-order.svg
  .gitbook/assets/b2b-architecture-users.svg
  SUMMARY.md
  products/editions/enterprise-edition/b2b-suite/README.md
  products/editions/enterprise-edition/b2b-suite/concepts/README.md
  products/editions/enterprise-edition/b2b-suite/concepts/basic-conventions.md
  products/editions/enterprise-edition/b2b-suite/concepts/method-structure.md
  products/editions/enterprise-edition/b2b-suite/concepts/system-architecture.md
Labels: Enterprise Team, Concept
