Repository shopware/docs, pull requests merged in 2022-05, with the labels that each got.

#564 Clear up snippet folder for those extending existing modules
  guides/plugins/plugins/administration/adding-snippets.md
Labels: Improvement

#501 NEXT-16225 - Added custom entities documentation
  SUMMARY.md
  guides/plugins/apps/administration/README.md
  guides/plugins/apps/app-scripts/README.md
  guides/plugins/apps/app-scripts/cart-manipulation.md
  guides/plugins/apps/custom-data/README.md
  guides/plugins/apps/custom-data/custom-entities.md
  guides/plugins/apps/custom-data/custom-fields.md
  resources/references/app-reference/entities-reference.md
Labels: Core Team

#576 Update systemd service template
  guides/hosting/infrastructure/message-queue.md
Labels: Faulty Documentation

#554 B2B-871 - B2B-Suite storefront docs
  .gitbook/assets/ajax-panel-abstract.svg
  .gitbook/assets/ajax-panel-structure.svg
  .gitbook/assets/company-management.svg
  .gitbook/assets/contact-controller-complex-example.svg
  .gitbook/assets/product-search-options.png
  SUMMARY.md
  products/editions/enterprise-edition/b2b-suite/example-plugins/B2bTemplateExtension.zip
  products/editions/enterprise-edition/b2b-suite/example-plugins/README.md
  products/editions/enterprise-edition/b2b-suite/guides/README.md
  products/editions/enterprise-edition/b2b-suite/guides/administration/README.md
  products/editions/enterprise-edition/b2b-suite/guides/storefront/README.md
  products/editions/enterprise-edition/b2b-suite/guides/storefront/acl-routing.md
  products/editions/enterprise-edition/b2b-suite/guides/storefront/ajax-panel.md
  products/editions/enterprise-edition/b2b-suite/guides/storefront/company.md
  products/editions/enterprise-edition/b2b-suite/guides/storefront/complex-views.md
  products/editions/enterprise-edition/b2b-suite/guides/storefront/how-to-extend-the-storefront.md
  products/editions/enterprise-edition/b2b-suite/guides/storefront/modal-component.md
  products/editions/enterprise-edition/b2b-suite/guides/storefront/product-search.md
Labels: Enterprise Team, Concept

#561 B2B-872 - B2B-Suite core guides
  .gitbook/assets/acl-address-schema.svg
  .gitbook/assets/acl-architecture.svg
  .gitbook/assets/assignment-service.svg
  .gitbook/assets/audit_log_structure.svg
  .gitbook/assets/authentication-overview.svg
  .gitbook/assets/crud-service.svg
  .gitbook/assets/currency-usage.svg
  .gitbook/assets/line-item-list-outer-dependencies.svg
  .gitbook/assets/line-item-list-with-listing.svg
  .gitbook/assets/line-item-list-with-order-context.svg
  .gitbook/assets/line-item-list-with-order.svg
  .gitbook/assets/listing-service.svg
  SUMMARY.md
  products/editions/enterprise-edition/b2b-suite/concepts/line-item-list.md
  products/editions/enterprise-edition/b2b-suite/guides/README.md
  products/editions/enterprise-edition/b2b-suite/guides/core/README.md
  products/editions/enterprise-edition/b2b-suite/guides/core/assignment-service.md
  products/editions/enterprise-edition/b2b-suite/guides/core/audit-log.md
  products/editions/enterprise-edition/b2b-suite/guides/core/authentication.md
  products/editions/enterprise-edition/b2b-suite/guides/core/crud-service.md
  products/editions/enterprise-edition/b2b-suite/guides/core/currency.md
  products/editions/enterprise-edition/b2b-suite/guides/core/dependency-injection.md
  products/editions/enterprise-edition/b2b-suite/guides/core/entity-acl.md
  products/editions/enterprise-edition/b2b-suite/guides/core/exception.md
  products/editions/enterprise-edition/b2b-suite/guides/core/listing-service.md
  products/editions/enterprise-edition/b2b-suite/guides/core/overload-classes.md
  products/editions/enterprise-edition/b2b-suite/guides/core/rest-api.md
  products/editions/enterprise-edition/b2b-suite/guides/core/store-api.md
Labels: Enterprise Team, Guide

#577 B2B-877 - Update architecture UML
  .gitbook/assets/b2b-architecture-acl.png
  .gitbook/assets/b2b-architecture-acl.svg
  .gitbook/assets/b2b-architecture-component.png
  .gitbook/assets/b2b-architecture-component.svg
  .gitbook/assets/b2b-architecture-components-complete.png
  .gitbook/assets/b2b-architecture-components-complete.svg
  .gitbook/assets/b2b-architecture-order.png
  .gitbook/assets/b2b-architecture-order.svg
  .gitbook/assets/b2b-architecture-users.png
  .gitbook/assets/b2b-architecture-users.svg
  products/editions/enterprise-edition/b2b-suite/concepts/system-architecture.md
Labels: Enterprise Team

#578 fix links to entities.xml schema
  guides/plugins/apps/custom-data/custom-entities.md
  resources/references/app-reference/entities-reference.md
Labels: Core Team, Faulty Documentation

#545 Update add-cms-block.md for more consistency
  guides/plugins/plugins/content/cms/add-cms-block.md
Labels: Improvement

#583 Add step for install with valet+
  guides/installation/valet.md
Labels: Improvement

#585 B2B-868 - update b2b-suite example plugins
  products/editions/enterprise-edition/b2b-suite/example-plugins/B2bAcl.zip
  products/editions/enterprise-edition/b2b-suite/example-plugins/B2bAjaxPanel.zip
  products/editions/enterprise-edition/b2b-suite/example-plugins/B2bAuditLog.zip
  products/editions/enterprise-edition/b2b-suite/example-plugins/B2bAuth.zip
  products/editions/enterprise-edition/b2b-suite/example-plugins/B2bLogin.zip
  products/editions/enterprise-edition/b2b-suite/example-plugins/B2bRestApi.zip
  products/editions/enterprise-edition/b2b-suite/example-plugins/B2bServiceExtension.zip
  products/editions/enterprise-edition/b2b-suite/example-plugins/B2bTemplateExtension.zip
  products/editions/enterprise-edition/b2b-suite/example-plugins/README.md
Labels: Enterprise Team, Guide

#563 WIP: PaaS product page
  .gitbook/assets/fork-repository.png
  SUMMARY.md
  products/enterprise-cloud/README.md
  products/enterprise-cloud/build-deploy.md
  products/enterprise-cloud/cli-setup.md
  products/enterprise-cloud/elasticsearch.md
  products/enterprise-cloud/fastly.md
  products/enterprise-cloud/rabbitmq.md
  products/enterprise-cloud/repository.md
  products/enterprise-cloud/setup-template.md
  products/enterprise-cloud/theme-build.md
Labels: Guide

#586 B2B-916 - remove and port SW6 info from SW5 docs repo
  SUMMARY.md
  products/editions/enterprise-edition/b2b-suite.md
  products/editions/enterprise-edition/b2b-suite/concepts/line-item-list.md
  products/editions/enterprise-edition/b2b-suite/example-plugins/README.md
  products/editions/enterprise-edition/b2b-suite/guides/README.md
  products/editions/enterprise-edition/b2b-suite/guides/core/audit-log.md
  products/editions/enterprise-edition/b2b-suite/guides/core/authentication.md
  products/editions/enterprise-edition/b2b-suite/guides/core/crud-service.md
  products/editions/enterprise-edition/b2b-suite/guides/core/listing-service.md
  products/editions/enterprise-edition/b2b-suite/guides/core/overload-classes.md
  products/editions/enterprise-edition/b2b-suite/guides/core/rest-api.md
  products/editions/enterprise-edition/b2b-suite/guides/example-plugins/B2bAcl.zip
  products/editions/enterprise-edition/b2b-suite/guides/example-plugins/B2bAjaxPanel.zip
  products/editions/enterprise-edition/b2b-suite/guides/example-plugins/B2bAuditLog.zip
  products/editions/enterprise-edition/b2b-suite/guides/example-plugins/B2bAuth.zip
  products/editions/enterprise-edition/b2b-suite/guides/example-plugins/B2bLogin.zip
  products/editions/enterprise-edition/b2b-suite/guides/example-plugins/B2bRestApi.zip
  products/editions/enterprise-edition/b2b-suite/guides/example-plugins/B2bServiceExtension.zip
  products/editions/enterprise-edition/b2b-suite/guides/example-plugins/B2bTemplateExtension.zip
  products/editions/enterprise-edition/b2b-suite/guides/example-plugins/README.md
  products/editions/enterprise-edition/b2b-suite/guides/installation/README.md
  products/editions/enterprise-edition/b2b-suite/guides/storefront/acl-routing.md
Labels: Enterprise Team, Guide, Concept
