Repository shopware/docs, pull requests merged in 2022-03, with the labels that each got.

#507 fix: SyntaxError object instead of array
  guides/plugins/themes/theme-inheritance-configuration.md
Labels: Improvement

#511 broken link to create migration
  concepts/framework/migrations.md
Labels: Faulty Documentation

#497 NEXT-19965 - add custom endpoint script docs
  SUMMARY.md
  guides/plugins/apps/app-base-guide.md
  guides/plugins/apps/app-scripts/README.md
  guides/plugins/apps/app-scripts/custom-endpoints.md
  resources/references/app-reference/script-reference/custom-endpoint-script-services-reference.md
  resources/references/app-reference/script-reference/miscellaneous-script-services-reference.md
  resources/references/app-reference/script-reference/script-hooks-reference.md
Labels: Core Team

#513 Fixed cmd example style
  guides/installation/docker.md
  guides/installation/from-scratch.md
Labels: Improvement

#508 Expanded on adding a custom menu entry.
  guides/plugins/plugins/administration/add-menu-entry.md
Labels: Faulty Documentation

#520 NEXT-20435 - update payment docs for refund handling
  guides/plugins/plugins/checkout/payment/add-payment-plugin.md
Labels: Guide

#531 RUF-478 - Private app secret
  guides/plugins/apps/app-base-guide.md
Labels: Cloud Team

#522 Fixing Shell Script for Unit Testing Documentation
  guides/plugins/plugins/testing/php-unit.md
Labels: Faulty Documentation
