Repository shopware/docs, pull requests merged in 2022-10, with the labels that each got.

#683 fix: add missing form csrf handler
  guides/plugins/plugins/storefront/use-csrf-protection.md
Labels: Improvement, Faulty Documentation

#706 NTR - Update 'using-utils.md'
  SUMMARY.md
  guides/plugins/plugins/administration/using-utils.md
Labels: Improvement

#705 NTR - Refactor add-translations.md to also consider apps
  guides/plugins/plugins/storefront/add-translations.md
Labels: Improvement

#708 Add missing documentation of text-editor config input-field type
  guides/plugins/plugins/plugin-fundamentals/add-plugin-configuration.md
Labels: Admin Team

#704 fixed typo in cms-block guide
  guides/plugins/plugins/content/cms/add-cms-block.md
Labels: Storefront Team

#707 Fix typo error
  guides/plugins/plugins/framework/flow/add-flow-builder-action.md
Labels: Improvement, Faulty Documentation

#703 NEXT-23394 - Update documentation Flow Builder for next major
  guides/plugins/plugins/framework/flow/add-flow-builder-action.md
Labels: Improvement

#717 Add raw to inline twig example
  guides/plugins/plugins/administration/customizing-components.md
Labels: Improvement

#684 Update overview.md to use `trunk` as default branch
  guides/installation/overview.md
Labels: Improvement, Faulty Documentation

#701 Style guide added
  SUMMARY.md
  resources/guidelines/README.md
  resources/guidelines/documentation-guidelines/01-general.md
  resources/guidelines/documentation-guidelines/02-conceptual-structure.md
  resources/guidelines/documentation-guidelines/03-language-and-grammar.md
  resources/guidelines/documentation-guidelines/04-fonts-and-formats/01-text.md
  resources/guidelines/documentation-guidelines/04-fonts-and-formats/02-code.md
  resources/guidelines/documentation-guidelines/04-fonts-and-formats/README.md
  resources/guidelines/documentation-guidelines/05-methodize-assets.md
  resources/guidelines/documentation-guidelines/06-doc-process.md
  resources/guidelines/documentation-guidelines/README.md
  resources/guidelines/documentation/README.md
  resources/guidelines/documentation/structure.md
  resources/guidelines/documentation/templates/README.md
  resources/guidelines/documentation/templates/guide-documentation-template.md
  resources/guidelines/documentation/writing.md
Labels: Improvement, Guide

#758 Change symfony links to currently used symfony version 5.4
  guides/hosting/performance/session.md
Labels: Improvement, Guide, Faulty Documentation

#727 Update build-w-o-db: Partial build / remove example
  guides/hosting/installation-updates/deployments/build-w-o-db.md
Labels: Core Team, Improvement

#760 Flex
  .gitpod.yml
  .vscode/extensions.json
  .vscode/ltex.dictionary.en-US.txt
  SUMMARY.md
  guides/installation/flex.md
  guides/installation/overview.md
  products/paas/elasticsearch.md
  products/paas/fastly.md
  products/paas/rabbitmq.md
  products/paas/repository.md
  products/paas/setup-template.md
Labels: Improvement

#759 Revert #713
  .gitbook/assets/concept-api-storeApi-dataAndLogicFlow.png
  .gitbook/assets/concept-catalog-products-datamodel.png
  .gitbook/assets/concept-catalog-products-variantModel.png
  .gitbook/assets/concept-categories.png
  .gitbook/assets/concept-commerce-shopppingExperiences-resolvingCmsPage.png
  .gitbook/assets/readme-splash.png
  README.md
  concepts/api/store-api.md
  concepts/commerce/catalog/categories.md
  concepts/commerce/catalog/products.md
  concepts/commerce/core/shopping-experiences-cms.md
Labels: Improvement, Guide
