Repository shopware/docs, pull requests merged in 2023-01, with the labels that each got.

#818 Rename occurrences of "http" to "HTTP" in text passages
  SUMMARY.md
  concepts/framework/http_cache.md
  guides/hosting/infrastructure/elasticsearch/elasticsearch-setup.md
  guides/hosting/infrastructure/reverse-http-cache.md
  guides/hosting/performance/caches.md
  guides/integrations-api/general-concepts/api-versioning.md
  guides/plugins/apps/hosting-guide/README.md
  guides/plugins/plugins/storefront/add-caching-to-custom-controller.md
  guides/plugins/plugins/storefront/use-csrf-protection.md
  products/paas/setup-template.md
  resources/references/adr/api/2022-02-09-controller-configuration-route-defaults.md
Labels: Improvement, Guide

#814 NEXT-24778 - Add docs for Flow templates in Flow Buider
  concepts/framework/flow-concept.md
Labels: Undocumented Feature

#788 DX-199-update-testing-guidelines
  .gitbook/assets/guidelines-test-store-apiValidation.png
  .gitbook/assets/guidelines-test-store-plugin.png
  SUMMARY.md
  resources/guidelines/testing/store/README.md
  resources/guidelines/testing/store/quality-guidelines-apps/README.md
  resources/guidelines/testing/store/quality-guidelines-plugins/README.md
Labels: Improvement, QA Team

#825 NEXT-24809 - Add payment and shipping method route hooks
  resources/references/app-reference/script-reference/script-hooks-reference.md
Labels: Checkout Team

#767 feat: remove mamp
  SUMMARY.md
  guides/installation/README.md
  guides/installation/community/README.md
  guides/installation/community/dockware.md
  guides/installation/legacy/README.md
  guides/installation/legacy/docker.md
  guides/installation/legacy/from-scratch.md
  guides/installation/legacy/mamp.md
  guides/installation/legacy/valet.md
  guides/installation/overview.md
  resources/guidelines/documentation-guidelines/04-fonts-and-formats/01-text.md
Labels: Improvement

#809 Addition of guided shopping docs to dev docs : DX-230
  .gitbook/assets/products-guidedShopping-checklist.png
  .gitbook/assets/products-guidedShopping-extensionsMenu.png
  .gitbook/assets/products-guidedShopping-mercureConfig.png
  .gitbook/assets/products-guidedShopping-mercureConfigExample.png
  .gitbook/assets/products-guidedShopping-swagExtensionOnList.png
  .gitbook/assets/products-guidedShopping-uploadExtension.png
  .gitbook/assets/products-guidedShopping-videoConfig.png
  .gitbook/assets/products-guidedShopping.png
  SUMMARY.md
  products/guided-shopping/README.md
  products/guided-shopping/checklist.md
  products/guided-shopping/installation.md
  products/guided-shopping/sampleMercureConfig.md
  products/guided-shopping/selfHostedMercureInstallation.md
Labels: Undocumented Feature, Guide
