Repository shopware/docs, pull requests merged in 2023-09, with the labels that each got.

#1086 feat: add scheduled task page
  SUMMARY.md
  guides/hosting/infrastructure/scheduled-task.md
  resources/references/core-reference/commands-reference.md
Labels: Improvement, DX Team

#1092 NEXT-29750 - Write dev document for advanced search
  SUMMARY.md
  products/extensions/advanced-search/Cross-search.md
  products/extensions/advanced-search/How-to-add-modify-language-analyzers-stopwords-stemmer.md
  products/extensions/advanced-search/How-to-add-more-fields-to-product-search.md
  products/extensions/advanced-search/How-to-configure-searchable-fields.md
  products/extensions/advanced-search/How-to-define-your-custom-Elasticsearch-definition.md
  products/extensions/advanced-search/How-to-extend-the-search-and-suggest-template.md
  products/extensions/advanced-search/How-to-modify-completion.md
  products/extensions/advanced-search/How-to-modify-search-logic.md
  products/extensions/advanced-search/README.md
  products/extensions/advanced-search/Search-and-suggest-routes.md
  products/extensions/advanced-search/installation.md
  products/extensions/search/README.md
  products/extensions/search/boosting.md
  products/extensions/search/completion.md
  products/extensions/search/extensibility.md
  products/extensions/search/field-config.md
  products/extensions/search/installation.md
  products/extensions/search/relevance.md
  products/extensions/search/synonyms.md
Labels: Undocumented Feature, Inventory

#1080 Update flow builder actions docs for 6.4
  .gitbook/assets/flow-builder-action-available-all-events.png
  .gitbook/assets/flow-builder-triggers-list.png
  guides/plugins/plugins/framework/flow/add-flow-builder-action.md
Labels: Business Ops

#1102 Own composer dependecies
  resources/guidelines/testing/store/quality-guidelines-plugins/README.md
Labels: Improvement, DX Team

#1090 BC-44 Improve PaaS Recipe & Docs
  products/paas/build-deploy.md
  products/paas/repository.md
Labels: Improvement, DX Team

#1085 Update PHPunit docs
  guides/plugins/plugins/testing/php-unit.md
Labels: DX Team

#1087 Revamp installation guidelines
  guides/installation/README.md
  guides/installation/legacy/README.md
  guides/installation/legacy/docker.md
  guides/installation/legacy/from-scratch.md
  guides/installation/legacy/mamp.md
  guides/installation/legacy/valet.md
Labels: Improvement, DX Team

#1104 NEXT-30352 - Add cluster setup config docs
  guides/hosting/installation-updates/cluster-setup.md
Labels: Blocked, Manual migration (DevHub)
