Repository shopware/docs, pull requests merged in 2023-06, with the labels that each got.

#964 Additional flag for media command
  resources/references/core-reference/commands-reference.md
Labels: Improvement

#940 There is no StoreApiClient in 6.5
  guides/plugins/plugins/storefront/fetching-data-with-javascript.md
Labels: More Information Needed

#968 Additional docs for using nix with oh my combined with nix
  guides/installation/devenv.md
Labels: Undocumented Feature, DX Team

#978 Update plugin-lifecycle.md
  guides/plugins/plugins/plugin-fundamentals/plugin-lifecycle.md
Labels: Core Team, Faulty Documentation

#976 bootstap 5 update
  guides/plugins/plugins/storefront/using-a-modal-window.md
Labels: Faulty Documentation, Storefront Team

#981 Fix typo in README.md
  products/extensions/migration-assistant/concept/README.md
Labels: Faulty Documentation
