Repository shopware/docs, pull requests merged in 2023-07, with the labels that each got.

#973 NEXT-26976 - Adding two guides for creating own permissions
  SUMMARY.md
  products/extensions/b2b-components/README.md
  products/extensions/b2b-components/guides/README.md
  products/extensions/b2b-components/guides/creating-own-permissions-via-app.md
  products/extensions/b2b-components/guides/creating-own-permissions-via-plugin.md
Labels: Improvement

#995 NEXT-29147 - Add warning about twig use usage
  resources/references/storefront-reference/twig-function-reference.md
Labels: Improvement

#1004 Update README.md
  resources/guidelines/testing/store/quality-guidelines-plugins/README.md
Labels: Improvement

#1003 Update README.md
  resources/guidelines/testing/store/quality-guidelines-apps/README.md
Labels: Improvement

#1002 Update add-custom-controller.md
  guides/plugins/plugins/storefront/add-custom-controller.md
Labels: Improvement

#999 Update add-product-entity-extension-to-elasticsearch.md. Add missing buildTermQuery function
  guides/plugins/plugins/elasticsearch/add-product-entity-extension-to-elasticsearch.md
Labels: Core Team, Improvement, Storefront Team

#982 NEXT-25815 - Recurring payments
  guides/plugins/apps/payment.md
  guides/plugins/plugins/checkout/payment/add-payment-plugin.md
Labels: Improvement, DX Team, Checkout Team

#998 Remove csrf doc and add info about SameSite attribute
  .gitbook.yaml
  SUMMARY.md
  guides/hosting/configurations.md
  guides/hosting/configurations/framework.md
  guides/hosting/configurations/framework/samesite-protection.md
  guides/hosting/configurations/shopware.md
  guides/hosting/configurations/shopware/html-sanitizer.md
  guides/plugins/plugins/storefront/use-csrf-protection.md
  guides/security/README.md
  resources/references/security.md
  resources/references/storefront-reference/twig-function-reference.md
Labels: DX Team

#1021 Merged all there changes into one PR and adjusted links
  resources/guidelines/testing/store/quality-guidelines-apps/README.md
  resources/guidelines/testing/store/quality-guidelines-plugins/README.md
Labels: Improvement

#1024 Update for the new naming scheme qualiy-guidelines-apps
  resources/guidelines/testing/store/quality-guidelines-apps/README.md
Labels: Improvement, QA Team

#1005 NEXT-28562 - Added guide how to tweak/manipulate cache invalidation
  SUMMARY.md
  guides/hosting/performance/custom-cache-invalidation.md
Labels: Undocumented Feature, DX Team

#1020 NEXT-29168 - Add composer dependency security update guide
  guides/hosting/installation-updates/cluster-setup.md
Labels: Core Team, Undocumented Feature

#1027 Issue 550 - hint added
  guides/installation/requirements.md
Labels: Core Team, Info Missed To Document
