Repository shopware/docs, pull requests merged in 2023-08, with the labels that each got.

#1016 NEXT-29107 - B2B Route Restriction
  products/extensions/b2b-components/employee-management/concept/api-route-restriction-for-employees.md
Labels: Undocumented Feature

#1032 Enable mermaid diagram
  .gitbook/assets/b2b-employee-management-er-schema.png
  products/extensions/b2b-components/employee-management/concept/entities-and-schema.md
Labels: Improvement, DX Team

#1015 Explain context in DAL section
  concepts/framework/data-abstraction-layer.md
Labels: Core, Improvement

#1028 Add foreign key info and warning about recursion
  guides/plugins/plugins/framework/data-handling/add-complex-data-to-existing-entities.md
  guides/plugins/plugins/framework/data-handling/add-data-associations.md
Labels: Improvement, DX Team

#1033 Update performance-tweaks.md
  guides/hosting/performance/performance-tweaks.md
Labels: Faulty Documentation, DX Team

#1034 Update performance-tweaks.md
  guides/hosting/performance/performance-tweaks.md
Labels: Faulty Documentation, DX Team

#1037 Update directory diagram for extended administration modules
  guides/plugins/plugins/administration/add-new-tab.md
Labels: Faulty Documentation, DX Team

#1014 feat: add storefront to app server communication
  SUMMARY.md
  guides/plugins/apps/app-base-guide.md
  guides/plugins/apps/clientside-to-app-backend.md
Labels: Core, Undocumented Feature

#1036 PaaS documentation
  products/paas/build-deploy.md
  products/paas/repository.md
  products/paas/theme-build.md
Labels: Improvement, DX Team

#1010 Add instructions for using custom fields in forms in storefront
  guides/plugins/plugins/storefront/using-custom-fields-storefront.md
Labels: Improvement, DX Team

#710 Add a guide for creating own twig functions with new example
  SUMMARY.md
  guides/plugins/plugins/storefront/add-custom-twig-function.md
Labels: Improvement, Guide, Storefront

#1051 NEXT-29563 - Renamed company to business partner in employee management
  SUMMARY.md
  products/extensions/b2b-components/employee-management/README.md
  products/extensions/b2b-components/employee-management/concept/entities-and-schema.md
  products/extensions/b2b-components/employee-management/guides/creating-own-permissions-via-app.md
Labels: B2B

#1040 Add PaaS step-by-step overview + change setup-template for Symfony Flex
  products/paas/README.md
  products/paas/setup-template.md
Labels: Improvement, DX Team

#1066 Renaming the term GS
  .gitbook/assets/products-digitalSalesRooms-display.png
  .gitbook/assets/products-digitalSalesRooms-extensionsMenu.png
  .gitbook/assets/products-digitalSalesRooms-installExtension.png
  .gitbook/assets/products-digitalSalesRooms-mercureConfig.png
  .gitbook/assets/products-digitalSalesRooms-mercureConfigExample.png
  .gitbook/assets/products-digitalSalesRooms-mercureConfiguration.png
  .gitbook/assets/products-digitalSalesRooms-swagExtensionInstall.png
  .gitbook/assets/products-digitalSalesRooms-uploadExtension.png
  .gitbook/assets/products-digitalSalesRooms-videoConfig.png
  .gitbook/assets/products-digitalSalesRooms.png
  .gitbook/assets/products-guidedShopping-checklist.png
  SUMMARY.md
  products/guided-shopping/README.md
  products/guided-shopping/checklist.md
  products/guided-shopping/installation.md
  products/guided-shopping/sampleMercureConfig.md
  products/guided-shopping/selfHostedMercureInstallation.md
Labels: DX Team

#1076 Update docs
  guides/plugins/plugins/framework/custom-field/add-custom-field.md
Labels: Improvement

#1088 feat: add worker amount faq
  guides/hosting/infrastructure/message-queue.md
Labels: Improvement, DX Team

#1081 Extending services Code Example Update
  guides/plugins/plugins/administration/extending-services.md
Labels: Faulty Documentation, Admin

#1095 feat: add extension management page
  SUMMARY.md
  guides/hosting/installation-updates/composer.md
  guides/hosting/installation-updates/extension-managment.md
Labels: Improvement
