Repository shopware/docs, pull requests merged in 2023-02, with the labels that each got.

#838 Add documentation for afterOrderEnabled property
  guides/plugins/plugins/checkout/payment/add-payment-plugin.md
Labels: Improvement, Checkout Team

#839 NEXT-25172 - Update doc for Add Flow Builder trigger
  guides/plugins/plugins/framework/flow/add-flow-builder-action.md
  guides/plugins/plugins/framework/flow/add-flow-builder-trigger.md
Labels: Improvement

#836 add `devenv shell` command
  guides/installation/devenv.md
Labels: Info Missed To Document

#840 DX-273 - Fix broken links
  SUMMARY.md
  concepts/commerce/catalog/sales-channels.md
  concepts/framework/elasticsearch.md
  guides/hosting/infrastructure/elasticsearch/README.md
  guides/hosting/infrastructure/elasticsearch/elasticsearch-debugging.md
  guides/hosting/infrastructure/elasticsearch/elasticsearch-setup.md
  guides/hosting/performance/performance-tweaks.md
  guides/installation/community/dockware.md
  guides/installation/legacy/docker.md
  guides/installation/legacy/from-scratch.md
  guides/installation/legacy/mamp.md
  guides/installation/legacy/valet.md
  guides/plugins/apps/configuration.md
  guides/plugins/apps/rule-builder/add-custom-rule-conditions.md
  guides/plugins/plugins/api/README.md
  guides/plugins/plugins/elasticsearch/README.md
  products/community-edition.md
  products/extensions/b2b-suite/guides/installation/README.md
  products/guided-shopping/README.md
Labels: Improvement, DX Team

#841 DX-274 - Update image paths
  .gitbook/assets/adr/tideways_benchmark.png
  .github/scripts/update-adrs.sh
  products/extensions/b2b-suite/concepts/line-item-list.md
  products/extensions/b2b-suite/concepts/system-architecture.md
  products/extensions/b2b-suite/guides/core/assignment-service.md
  products/extensions/b2b-suite/guides/core/audit-log.md
  products/extensions/b2b-suite/guides/core/authentication.md
  products/extensions/b2b-suite/guides/core/crud-service.md
  products/extensions/b2b-suite/guides/core/currency.md
  products/extensions/b2b-suite/guides/core/entity-acl.md
  products/extensions/b2b-suite/guides/core/listing-service.md
  products/extensions/b2b-suite/guides/storefront/ajax-panel.md
  products/extensions/b2b-suite/guides/storefront/company.md
  products/extensions/b2b-suite/guides/storefront/complex-views.md
  products/extensions/b2b-suite/guides/storefront/product-search.md
  resources/references/adr/checkout/2021-10-01-payment-flow.md
  resources/references/adr/performance/2022-03-25-profiler-integrations.md
Labels: Improvement, DX Team

#779 NEXT-23917 - Remove mentions of EntityRepositoryInterface
  concepts/framework/data-abstraction-layer.md
  guides/plugins/plugins/checkout/payment/add-payment-plugin.md
  guides/plugins/plugins/content/seo/add-custom-seo-url.md
  guides/plugins/plugins/content/sitemap/add-custom-sitemap-entries.md
  guides/plugins/plugins/framework/custom-field/fetching-data-from-entity-selection.md
  guides/plugins/plugins/framework/data-handling/add-data-indexer.md
  guides/plugins/plugins/framework/data-handling/reading-data.md
  guides/plugins/plugins/framework/data-handling/writing-data.md
  guides/plugins/plugins/framework/flow/add-flow-builder-action.md
  guides/plugins/plugins/framework/store-api/add-store-api-route.md
  guides/plugins/plugins/framework/store-api/override-existing-route.md
  products/extensions/migration-assistant/concept/gateway-and-reader.md
  products/extensions/migration-assistant/guides/decorating-a-shopware-migration-assistant-converter.md
Labels: Blocked, DX Team

#847 Update finding events docs
  guides/plugins/plugins/framework/event/finding-events.md
Labels: Guide, Blocked, Info Missed To Document

#851 Add saleschannelid field and note
  guides/plugins/plugins/plugin-fundamentals/use-plugin-configuration.md
Labels: Improvement, Guide

#805 NEXT-21725 - Update message queue document for next major
  .gitbook/assets/products-guidedShopping-checklist.png
  .gitbook/assets/products-guidedShopping-extensionsMenu.png
  .gitbook/assets/products-guidedShopping-mercureConfig.png
  .gitbook/assets/products-guidedShopping-mercureConfigExample.png
  .gitbook/assets/products-guidedShopping-swagExtensionOnList.png
  .gitbook/assets/products-guidedShopping-uploadExtension.png
  .gitbook/assets/products-guidedShopping-videoConfig.png
  .gitbook/assets/products-guidedShopping.png
  SUMMARY.md
  concepts/framework/messaging.md
  guides/hosting/infrastructure/filesystem.md
  guides/hosting/infrastructure/message-queue.md
  guides/hosting/installation-updates/composer.md
  guides/plugins/plugins/framework/message-queue/add-message-handler.md
  guides/plugins/plugins/framework/message-queue/add-message-to-queue.md
  products/guided-shopping/README.md
  products/guided-shopping/checklist.md
  products/guided-shopping/installation.md
  products/guided-shopping/sampleMercureConfig.md
  products/guided-shopping/selfHostedMercureInstallation.md
Labels: Improvement

#854 Update add-mixins.md
  guides/plugins/plugins/administration/add-mixins.md
Labels: Improvement, Faulty Documentation

#857 Remove deprecations in app system guides; use manifest-2.0.xml in exa…
  guides/plugins/apps/administration/add-custom-action-button.md
  guides/plugins/apps/administration/add-custom-modules.md
  guides/plugins/apps/app-base-guide.md
  guides/plugins/apps/custom-data/custom-entities.md
  guides/plugins/apps/custom-data/custom-fields.md
  guides/plugins/apps/flow-builder/add-custom-flow-actions-from-app-system.md
  guides/plugins/apps/payment.md
  guides/plugins/apps/rule-builder/add-custom-rule-conditions.md
  guides/plugins/apps/starter/add-api-endpoint.md
  guides/plugins/apps/starter/product-translator.md
  guides/plugins/apps/starter/starter-admin-extension.md
  guides/plugins/apps/storefront/cookies-with-apps.md
  resources/references/app-reference/manifest-reference.md
Labels: Improvement

#829 NEXT-24647 - add MultiInventory page
  SUMMARY.md
  guides/plugins/plugins/api/customer-specific-pricing.md
  guides/plugins/plugins/api/multi-inventory.md
Labels: Undocumented Feature, Guide

#843 Rework the setup guides and Requirements
  SUMMARY.md
  guides/hosting/installation-updates/composer.md
  guides/installation/README.md
  guides/installation/requirements.md
  guides/installation/template.md
  guides/plugins/plugins/plugin-base-guide.md
  products/community-edition.md
Labels: Improvement

#867 fix duplicate app in path for custom component
  guides/plugins/plugins/administration/add-custom-component.md
Labels: Improvement, Guide

#860 Added STP tracking and an example in Quality guidelines for apps in plugin system
  resources/guidelines/testing/store/quality-guidelines-apps/README.md
  resources/guidelines/testing/store/quality-guidelines-plugins/README.md
Labels: Undocumented Feature, Guide

#817 NEXT-20706 - Add the missing keys to the shopware.yaml configuration
  guides/hosting/infrastructure/filesystem.md
Labels: Improvement
