Repository shopware/docs, pull requests merged in 2023-10, with the labels that each got.

#1130 Fix app template load priority in reference and docs
  guides/plugins/apps/storefront/index.md
  resources/references/app-reference/manifest-reference.md
Labels: hacktoberfest-accepted

#1131 Fix json ending and add override info
  guides/plugins/apps/custom-data/custom-entities.md
  guides/plugins/apps/flow-builder/add-custom-flow-triggers-from-app-system.md
  guides/plugins/plugins/checkout/cart/add-cart-validator.md
  guides/plugins/plugins/framework/store-api/add-store-api-route.md
  guides/plugins/plugins/plugin-base-guide.md
  guides/plugins/plugins/plugin-fundamentals/add-plugin-dependencies.md
  guides/plugins/plugins/storefront/add-custom-styling.md
  guides/plugins/plugins/storefront/add-translations.md
  guides/plugins/themes/add-theme-inheritance-without-resources.md
  guides/plugins/themes/add-theme-inheritance.md
  guides/plugins/themes/override-bootstrap-variables-in-a-theme.md
  guides/plugins/themes/theme-configuration.md
  guides/plugins/themes/theme-inheritance-configuration.md
Labels: DX Team, hacktoberfest-accepted

#1139 NEXT-30116 - Document for B2B Customer Specific Features
  assets/b2b-feature-toggles.png
  products/extensions/b2b-components/customer-specific-features/feature-toggles.md
  products/extensions/b2b-components/customer-specific-features/index.md
Labels: DX Team, B2B

#1149 Add docs how to add script tags to Storefront HTML
  guides/plugins/plugins/storefront/add-javascript-as-script-tag.md
Labels: Storefront

#1152 Fix event/entity and grammar changes
  guides/plugins/plugins/framework/event/add-custom-event.md
  guides/plugins/plugins/framework/flow/add-flow-builder-trigger.md
Labels: Faulty Documentation

#1157 DX-471 - Move files, folders and sorting of b2b extensions
  products/extensions/b2b-components/customer-specific-features/feature-toggles.md
  products/extensions/b2b-components/customer-specific-features/index.md
  products/extensions/b2b-components/employee-management/concept/api-route-restriction-for-employees.md
  products/extensions/b2b-components/employee-management/concept/entities-and-schema.md
  products/extensions/b2b-components/employee-management/concept/index.md
  products/extensions/b2b-components/employee-management/guides/b2b-employee-invite-registration.md
  products/extensions/b2b-components/employee-management/guides/b2b-roles.md
  products/extensions/b2b-components/employee-management/guides/creating-own-permissions-via-app.md
  products/extensions/b2b-components/employee-management/guides/creating-own-permissions-via-plugin.md
  products/extensions/b2b-components/employee-management/guides/index.md
  products/extensions/b2b-components/employee-management/index.md
  products/extensions/b2b-components/index.md
  products/extensions/b2b-suite/concept/basic-conventions.md
  products/extensions/b2b-suite/concept/index.md
  products/extensions/b2b-suite/concept/line-item-list.md
  products/extensions/b2b-suite/concept/method-structure.md
  products/extensions/b2b-suite/concept/system-architecture.md
  products/extensions/b2b-suite/guides/administration/index.md
  products/extensions/b2b-suite/guides/core/assignment-service.md
  products/extensions/b2b-suite/guides/core/audit-log.md
  products/extensions/b2b-suite/guides/core/authentication.md
  products/extensions/b2b-suite/guides/core/crud-service.md
  products/extensions/b2b-suite/guides/core/currency.md
  products/extensions/b2b-suite/guides/core/dependency-injection.md
  products/extensions/b2b-suite/guides/core/entity-acl.md
  products/extensions/b2b-suite/guides/core/exception.md
  products/extensions/b2b-suite/guides/core/index.md
  products/extensions/b2b-suite/guides/core/listing-service.md
  products/extensions/b2b-suite/guides/core/overload-classes.md
  products/extensions/b2b-suite/guides/core/rest-api.md
  products/extensions/b2b-suite/guides/core/store-api.md
  products/extensions/b2b-suite/guides/example-plugins/B2bAcl.zip
  products/extensions/b2b-suite/guides/example-plugins/B2bAjaxPanel.zip
  products/extensions/b2b-suite/guides/example-plugins/B2bAuditLog.zip
  products/extensions/b2b-suite/guides/example-plugins/B2bAuth.zip
  products/extensions/b2b-suite/guides/example-plugins/B2bLogin.zip
  products/extensions/b2b-suite/guides/example-plugins/B2bRestApi.zip
  products/extensions/b2b-suite/guides/example-plugins/B2bServiceExtension.zip
  products/extensions/b2b-suite/guides/example-plugins/B2bTemplateExtension.zip
  products/extensions/b2b-suite/guides/example-plugins/index.md
  products/extensions/b2b-suite/guides/index.md
  products/extensions/b2b-suite/guides/installation/index.md
  products/extensions/b2b-suite/guides/storefront/acl-routing.md
  products/extensions/b2b-suite/guides/storefront/ajax-panel.md
  products/extensions/b2b-suite/guides/storefront/company.md
  products/extensions/b2b-suite/guides/storefront/complex-views.md
  products/extensions/b2b-suite/guides/storefront/how-to-extend-the-storefront.md
  products/extensions/b2b-suite/guides/storefront/index.md
  products/extensions/b2b-suite/guides/storefront/modal-component.md
  products/extensions/b2b-suite/guides/storefront/product-search.md
  products/extensions/b2b-suite/index.md
  products/extensions/b2b/b2b-components/employee-management/concept/index.md
  products/extensions/b2b/b2b-components/employee-management/guides/index.md
  products/extensions/b2b/index.md
Labels: Faulty Documentation, B2B

#1151 Add specific section for CDN and fix language and grammar
  guides/hosting/infrastructure/filesystem.md
Labels: Improvement
