Repository shopware/docs, pull requests merged in 2024-04, with the labels that each got.

#1338 feat: update dsr docs
  .wordlist.txt
  assets/products-digitalSalesRooms-configuration.png
  assets/products-digitalSalesRooms-installExtension.png
  assets/products-digitalSalesRooms-mercureConfigExample.png
  assets/products-digitalSalesRooms-videoConfig.png
  assets/products-digitalSalesRooms.png
  products/digital-sales-rooms/index.md
  products/digital-sales-rooms/installation.md
  products/digital-sales-rooms/sampleMercureConfig.md
  products/digital-sales-rooms/selfHostedMercureInstallation.md
  products/guided-shopping/checklist.md
  products/guided-shopping/installation.md
Labels: v6.5

#1339 feat: update dsr docs 6.6
  .wordlist.txt
  assets/products-digitalSalesRooms-configuration.png
  assets/products-digitalSalesRooms-installExtension.png
  assets/products-digitalSalesRooms-mercureConfigExample.png
  assets/products-digitalSalesRooms-videoConfig.png
  assets/products-digitalSalesRooms.png
  products/digital-sales-rooms/index.md
  products/digital-sales-rooms/installation.md
  products/digital-sales-rooms/sampleMercureConfig.md
  products/digital-sales-rooms/selfHostedMercureInstallation.md
  products/guided-shopping/checklist.md
  products/guided-shopping/installation.md
Labels: +v6.6

#1324 Expand rule docs
  guides/plugins/plugins/framework/rule/add-custom-rules.md
Labels: Blocked

#1342 Add info on plugin folders
  guides/plugins/plugins/index.md
Labels: Core

#1344 NEXT-33933 - Improved employee invitation docs
  products/extensions/b2b-components/employee-management/guides/b2b-employee-invitation.md
  products/extensions/b2b-components/employee-management/guides/b2b-employee-invite-registration.md
Labels: B2B

#1356 feat: update dev docs
  .wordlist.txt
  assets/setup-domain-for-sales-channel-DSR.png
  products/digital-sales-rooms/configuration.md
  products/digital-sales-rooms/index.md
  products/digital-sales-rooms/installation.md
  products/digital-sales-rooms/installation/admin-installation.md
  products/digital-sales-rooms/installation/app-installation.md
  products/digital-sales-rooms/installation/index.md
  products/digital-sales-rooms/installation/realtime-service-mercure.md
  products/digital-sales-rooms/installation/realtime-video-dailyco.md
  products/digital-sales-rooms/sampleMercureConfig.md
  products/digital-sales-rooms/selfHostedMercureInstallation.md
Labels: DX Team, new

#1363 Update dev docs 6.5
  .wordlist.txt
  assets/setup-domain-for-sales-channel-DSR.png
  products/digital-sales-rooms/configuration.md
  products/digital-sales-rooms/index.md
  products/digital-sales-rooms/installation.md
  products/digital-sales-rooms/installation/admin-installation.md
  products/digital-sales-rooms/installation/app-installation.md
  products/digital-sales-rooms/installation/index.md
  products/digital-sales-rooms/installation/realtime-service-mercure.md
  products/digital-sales-rooms/installation/realtime-video-dailyco.md
  products/digital-sales-rooms/sampleMercureConfig.md
  products/digital-sales-rooms/selfHostedMercureInstallation.md
Labels: v6.5

#1364 Update redirect links
  products/digital-sales-rooms/index.md
  products/digital-sales-rooms/installation/admin-installation.md
Labels: +v6.6

#1357 feat: add deployment helper
  guides/hosting/installation-updates/deployments/deployment-helper.md
Labels: DX Team, new

#1347 Fix docs for custom admin search
  guides/plugins/plugins/administration/search-custom-data.md
Labels: DX Team, patch

#1354 Adjust code examples
  guides/plugins/apps/content/cms/add-custom-cms-blocks.md
  guides/plugins/plugins/administration/using-assets.md
  guides/plugins/plugins/content/cms/add-cms-block.md
  guides/plugins/plugins/content/cms/add-cms-element.md
Labels: Admin, patch

#1349 Add release files
  .github/release.yml
  .github/workflows/release-note.yml
Labels: DX Team
