Repository shopware/docs, pull requests merged in 2024-08, with the labels that each got.

#1431 NEXT-37105 - new payment handling
  guides/plugins/plugins/checkout/payment/add-payment-plugin.md
Labels: v6.6.5.0

#1426 NEXT-37105 - new payment handling for 6.7
  guides/plugins/apps/payment.md
  guides/plugins/plugins/checkout/payment/add-payment-plugin.md
  guides/plugins/plugins/checkout/payment/customize-payment-provider.md
  snippets/config/app/payments.xml
Labels: Blocked, v6.7

#1450 Update dev document for DSR
  assets/products-digitalSalesRooms-wildcard.png
  products/digital-sales-rooms/app-deployment/cloudflare.md
  products/digital-sales-rooms/app-deployment/index.md
  products/digital-sales-rooms/configuration.md
  products/digital-sales-rooms/configuration/domain-config.md
  products/digital-sales-rooms/configuration/index.md
  products/digital-sales-rooms/configuration/plugin-config.md
  products/digital-sales-rooms/index.md
  products/digital-sales-rooms/installation/admin-installation.md
  products/digital-sales-rooms/installation/app-installation.md
  products/digital-sales-rooms/installation/index.md
  products/digital-sales-rooms/local-installation/admin-side-installation.md
  products/digital-sales-rooms/local-installation/app-installation.md
  products/digital-sales-rooms/local-installation/index.md
  products/digital-sales-rooms/saas/index.md
  products/digital-sales-rooms/setup-3rd-party/index.md
  products/digital-sales-rooms/setup-3rd-party/realtime-service-mercure.md
  products/digital-sales-rooms/setup-3rd-party/realtime-video-dailyco.md
Labels: DX Team

#1444 Add varnish example to devenv setup
  guides/installation/devenv.md
Labels: Core
