Repository shopware/docs, pull requests merged in 2024-06, with the labels that each got.

#1390 NEXT-31522 - Added documentation for entity attributes
  .wordlist.txt
  guides/plugins/plugins/framework/data-handling/entities-via-attributes.md
Labels: v6.6.3.0

#1402 feat: add documentation on how to embed external repos to DevHub
  .wordlist.txt
  resources/guidelines/documentation-guidelines/07-embedding-external-repositories.md
Labels: Undocumented Feature, DX Team, Resources

#1397 Add custom approval rule by app
  assets/approval-rule-condition-multi-select-example.png
  assets/approval-rule-condition-single-select-example.png
  assets/approval-rule-condition-text-field-example.png
  assets/approval-rule-condition.png
  products/extensions/b2b-components/order-approval/guides/04-add-new-approval-condition.md
  snippets/config/app/approval-rule-conditions.xml
Labels: v6.6.4.0
