Repository shopware/docs, pull requests merged in 2024-07, with the labels that each got.

#1361 remove twig cache changing path
  guides/hosting/performance/caches.md
Labels: v6.6.4.0

#1391 feat: add info about making extension manager readonly
  guides/hosting/installation-updates/extension-managment.md
Labels: v6.6.4.0

#1406 feat: add static system config docs
  guides/hosting/configurations/shopware/static-system-config.md
Labels: v6.6.4.0

#1394 feat: add zstd for performance tweaks
  .wordlist.txt
  guides/hosting/performance/performance-tweaks.md
Labels: v6.6.4.0

#1425 NEXT-37038 - Remote thumbnail generation docs
  guides/plugins/plugins/content/media/remote-thumbnail-generation.md
Labels: System & Setting, v6.6.4.0

#1433 NEXT-37040: Subscription documentation
  .wordlist.txt
  products/extensions/index.md
  products/extensions/subscriptions/concept.md
  products/extensions/subscriptions/guides/events.md
  products/extensions/subscriptions/guides/index.md
  products/extensions/subscriptions/guides/request-scoping.md
  products/extensions/subscriptions/guides/template-scoping.md
  products/extensions/subscriptions/index.md
Labels: Guide, Checkout
