Repository shopware/docs, pull requests merged in 2025-06, with the labels that each got.

#1792 DX-608
  .gitbook.yaml
  .wordlist.txt
  products/paas/platformsh/blackfire.md
  products/paas/platformsh/build-deploy.md
  products/paas/platformsh/cli-setup.md
  products/paas/platformsh/elasticsearch.md
  products/paas/platformsh/fastly.md
  products/paas/platformsh/index.md
  products/paas/platformsh/rabbitmq.md
  products/paas/platformsh/repository.md
  products/paas/platformsh/setup-template.md
  products/paas/shopware/CLI/account.md
  products/paas/shopware/CLI/applications.md
  products/paas/shopware/CLI/command.md
  products/paas/shopware/CLI/exec.md
  products/paas/shopware/CLI/index.md
  products/paas/shopware/CLI/open.md
  products/paas/shopware/CLI/organizations.md
  products/paas/shopware/CLI/project.md
  products/paas/shopware/CLI/repository.md
  products/paas/shopware/CLI/vault.md
  products/paas/shopware/CLI/watch.md
  products/paas/shopware/faq.md
  products/paas/shopware/index.md
  products/paas/shopware/known-issues.md
  products/paas/shopware/project_setup.md
  products/paas/shopware/setup-shopware-for-paas.md
Labels: check-redirect

#1795 fix: redirect
  .gitbook.yaml
  products/paas/index.md
  products/paas/shopware-paas/blackfire.md
  products/paas/shopware-paas/build-deploy.md
  products/paas/shopware-paas/cli-setup.md
  products/paas/shopware-paas/elasticsearch.md
  products/paas/shopware-paas/fastly.md
  products/paas/shopware-paas/index.md
  products/paas/shopware-paas/rabbitmq.md
  products/paas/shopware-paas/repository.md
  products/paas/shopware-paas/setup-template.md
  products/paas/shopware/CLI/applications.md
  products/paas/shopware/CLI/index.md
  products/paas/shopware/CLI/open.md
  products/paas/shopware/CLI/organizations.md
  products/paas/shopware/CLI/project.md
  products/paas/shopware/CLI/repository.md
  products/paas/shopware/CLI/vault.md
  products/paas/shopware/CLI/watch.md
  products/paas/shopware/index.md
  products/paas/shopware/known-issues.md
  products/paas/shopware/project_setup.md
  products/paas/shopware/setup-shopware-for-paas.md
Labels: check-redirect

#1789 docs: context gateway
  devenv.lock
  guides/plugins/apps/gateways/context/command-reference.md
  guides/plugins/apps/gateways/context/context-gateway.md
Labels: v6.7

#1782 feat: add bundle docs
  guides/plugins/plugins/bundle.md
  guides/plugins/plugins/index.md
Labels: check-redirect

#1786 docs: Add guide for making API requests in administration plugins
  .wordlist.txt
  guides/plugins/plugins/administration/services-utilities/making-api-requests.md
Labels: Admin

#1801 Sync 'not allowed files' list with shopware-cli
  .wordlist.txt
  resources/guidelines/testing/store/quality-guidelines-apps/index.md
  resources/guidelines/testing/store/quality-guidelines-plugins/index.md
Labels: Info Missed To Document

#1423 v6.7.0.0-dev
  .github/scripts/update-adrs.sh
  .github/scripts/update-code-guidelines.sh
  .wordlist.txt
  devenv.lock
  guides/hosting/infrastructure/reverse-http-cache.md
  guides/hosting/performance/custom-cache-invalidation.md
  guides/hosting/performance/performance-tweaks.md
  guides/plugins/apps/administration/add-custom-action-button.md
  guides/plugins/apps/administration/add-custom-modules.md
  guides/plugins/apps/app-base-guide.md
  guides/plugins/apps/app-sdks/symfony-bundle/index.md
  guides/plugins/apps/custom-data/custom-entities.md
  guides/plugins/apps/flow-builder/add-custom-flow-actions-from-app-system.md
  guides/plugins/apps/flow-builder/add-custom-flow-triggers-from-app-system.md
  guides/plugins/apps/gateways/context/command-reference.md
  guides/plugins/apps/gateways/context/context-gateway.md
  guides/plugins/apps/payment.md
  guides/plugins/apps/shipping-methods.md
  guides/plugins/apps/starter/add-api-endpoint.md
  guides/plugins/apps/starter/product-translator.md
  guides/plugins/apps/starter/starter-admin-extension.md
  guides/plugins/apps/storefront/cookies-with-apps.md
  guides/plugins/apps/storefront/index.md
  guides/plugins/plugins/administration/templates-styling/using-assets.md
  guides/plugins/plugins/checkout/payment/add-payment-plugin.md
  guides/plugins/plugins/checkout/payment/customize-payment-provider.md
  guides/plugins/plugins/framework/caching/index.md
  guides/plugins/plugins/framework/store-api/add-caching-for-store-api-route.md
  guides/plugins/plugins/storefront/add-custom-controller.md
  guides/plugins/plugins/storefront/add-custom-page.md
  guides/plugins/plugins/storefront/add-custom-pagelet.md
  guides/plugins/plugins/storefront/add-custom-twig-function.md
  guides/plugins/plugins/storefront/add-data-to-storefront-page.md
  guides/plugins/plugins/storefront/add-dynamic-content-via-ajax-calls.md
  guides/plugins/plugins/storefront/customize-header-footer.md
  guides/plugins/plugins/storefront/customize-templates.md
  guides/plugins/themes/theme-configuration.md
  package.json
  resources/references/adr/2022-03-25-base-context-factory.md
  resources/references/app-reference/script-reference/cart-manipulation-script-services-reference.md
  resources/references/app-reference/script-reference/custom-endpoint-script-services-reference.md
  resources/references/app-reference/script-reference/data-loading-script-services-reference.md
  resources/references/app-reference/script-reference/miscellaneous-script-services-reference.md
  resources/references/app-reference/script-reference/product-script-services-reference.md
  resources/references/app-reference/script-reference/script-hooks-reference.md
  resources/references/storefront-reference/twig-function-reference.md
  snippets/config/app/approval-rule-conditions.xml
  snippets/config/app/cookies-group.xml
  snippets/config/app/cookies.xml
  snippets/config/app/custom-fields-simple.xml
  snippets/config/app/custom-fields.xml
  snippets/config/app/payments.xml
  snippets/config/app/permissions.xml
  snippets/config/app/rule-conditions.xml
  snippets/config/app/setup.xml
  snippets/config/app/shipping-methods.xml
  snippets/config/app/storefront.xml
  snippets/config/app/tax.xml
  snippets/config/app/webhooks.xml
Labels: Blocked, v6.7

#1805 check: deleted-files
  .github/workflows/redirect.yml
Labels: Blocked, check-deleted-file
