Repository shopware/docs, pull requests merged in 2025-02, with the labels that each got.

#1667 Update add-scheduled-task.md
  guides/plugins/plugins/plugin-fundamentals/add-scheduled-task.md
Labels: Core

#1675 docs: enhance licensing and feature management information in commerc…
  products/plugins/commercial/index.md
Labels: Improvement, Blocked

#1584 NEXT-39755 - Update messenger docs to use default symfony bus
  concepts/framework/messaging.md
  guides/hosting/infrastructure/message-queue.md
  guides/plugins/plugins/framework/message-queue/add-message-to-queue.md
  guides/plugins/plugins/framework/message-queue/add-middleware.md
Labels: Blocked
