Repository shopware/docs, pull requests merged in 2025-01, with the labels that each got.

#1627 Add another override example to devenv docs
  .wordlist.txt
  guides/installation/devenv.md
Labels: Improvement

#1673 docs: update docs for 6.7 instructions for the sdk
  guides/plugins/apps/administration/add-cms-element-via-admin-sdk.md
Labels: Blocked

#1674 docs: update vite documentation for migrating the custom webpack config
  guides/plugins/plugins/administration/system-updates/vite.md
Labels: Admin
